import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/ui/nav";
import QuestionContext, { QuestionProvider } from "@/contexts/questionContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QuestionProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}
        >
          <header className="flex-none">
            <Nav />
          </header>
          <main className="flex-grow overflow-auto bg-gray-50">{children}</main>
          <footer className="flex-none py-4 text-center text-sm text-gray-500 bg-gray-50">
            <a
              href="https://adc-ucf.com/"
              className="hover:underline"
              target="_blank"
            >
              For more information, visit our website
            </a>
            <br />© {new Date().getFullYear()} Lab Survey. All rights reserved.
          </footer>
        </body>
      </QuestionProvider>
    </html>
  );
}
